### ISSUE TITLE
Websocket errors

### ISSUE THREAD

**Issue by NadineLaCuisine** [EasyAI/Simple-Binance-Trader#11]
Hi!
Thank you for your work, I tried your trader but it kept spamming Websocket errors like this
 websocket:error from callback <bound method Binance_SOCK._on_Message of <binance_api.socket_master.Binance_SOCK object at 0x5465465465>>: _on_Message() takes 2 positional arguments but 3 were given

What is happening?

**Comment by EasyAI** [comment]
This has now fixed under the new binance_api update:
https://github.com/EasyAI/binance_api/tree/master/binance_api

**Comment by panpansh** [comment]
Same

```shell
PS C:\Users\k71\Desktop\Simple-Binance-Trader> python run.py
{'public_key': 'fsdfds', 'private_key': 'gfdgdffg', 'host_ip': '127.0.0.1', 'host_port': 9000, 'max_candles': 500, 'max_depth': 50, 'run_type': 'TEST', 'market_type': 'SPOT', 'update_bnb_balance': 'True', 'trader_interval': '15m', 'trading_currency': '0.002', 'trading_markets': ['BTC-ETH', 'BTC-LTC']}
2021-05-25 05:51:06,610:root:[BotCore] Initilizing the BotCore object.
2021-05-25 05:51:06,611:root:[BotCore] Starting the BotCore object.
2021-05-25 05:51:07,313:root:[BaseTrader][BTC-ETH] Initilizing trader object and empty attributes.
2021-05-25 05:51:07,314:root:[BaseTrader][BTC-ETH] Initilizing trader object attributes with data.
2021-05-25 05:51:07,315:root:[BaseTrader][BTC-LTC] Initilizing trader object and empty attributes.
2021-05-25 05:51:07,315:root:[BaseTrader][BTC-LTC] Initilizing trader object attributes with data.
Total 1k sets: 0.5
Candle sets: 0/0.5, ETA: 0s
Candle sets: 0.5/0.5, ETA: 0s
Total 1k sets: 0.5
Candle sets: 0/0.5, ETA: 0s
Candle sets: 0.5/0.5, ETA: 0s
2021-05-25 05:51:33,801:root:[SOCKET_MASTER] Socket error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2021-05-25 05:51:33,802:websocket:error from callback <bound method Binance_SOCK._on_Close of <binance_api.socket_master.Binance_SOCK object at 0x000002D934BC2D30>>: _on_Close() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "C:\Users\k71\Desktop\Simple-Binance-Trader\run.py", line 110, in <module>
    botCore.start(settings, LOGS_DIR, CACHE_DIR)
  File "C:\Users\k71\Desktop\Simple-Binance-Trader\core\botCore.py", line 413, in start
    core_object.start()
  File "C:\Users\k71\Desktop\Simple-Binance-Trader\core\botCore.py", line 241, in start
    self.socket_api.start()
  File "C:\Users\k71\Desktop\Simple-Binance-Trader\.venv\lib\site-packages\binance_api\socket_master.py", line 326, in start
    raise websocket.WebSocketTimeoutException('Couldn\'t connect to WS! Exiting.')
websocket._exceptions.WebSocketTimeoutException: Couldn't connect to WS! Exiting.
```
