### ISSUE TITLE
Websocket issue again

### ISSUE THREAD

**Issue by MikeKa** [EasyAI/Simple-Binance-Trader#13]
Hi @EasyAI !
Please suggest how to fix! Have the following... 

(enviroment_name) 17:29 ~/Simple-Binance-Trader (master)$ python3 run.py
2021-06-03 17:35:41,745:root:[BotCore] Initilizing the BotCore object.
2021-06-03 17:35:41,745:root:[BotCore] Starting the BotCore object.
2021-06-03 17:35:42,636:root:[BaseTrader][BTC-ETH] Initilizing trader object and empty attributes.
2021-06-03 17:35:42,636:root:[BaseTrader][BTC-ETH] Initilizing trader object attributes with data.
2021-06-03 17:35:42,636:root:[BaseTrader][BTC-LTC] Initilizing trader object and empty attributes.
2021-06-03 17:35:42,636:root:[BaseTrader][BTC-LTC] Initilizing trader object attributes with data.
Total 1k sets: 0.5
Candle sets: 0/0.5, ETA: 0s
Candle sets: 0.5/0.5, ETA: 0s
Total 1k sets: 0.5
Candle sets: 0/0.5, ETA: 0s
Candle sets: 0.5/0.5, ETA: 0s
2021-06-03 17:35:48,780:root:[SOCKET_MASTER] Socket error: failed CONNECT via proxy status: 403
2021-06-03 17:35:48,780:websocket:error from callback <bound method Binance_SOCK._on_Close of <core.binance_api.socket_master.Binance_SOCK object at 0x7f2723a9a250>>: _on_Close() takes 2 positional
 arguments but 4 were given
Traceback (most recent call last):
  File "run.py", line 112, in <module>
    botCore.start(settings, LOGS_DIR, CACHE_DIR)
  File "/home/Nosynq/Simple-Binance-Trader/core/botCore.py", line 502, in start
    core_object.start()
  File "/home/Nosynq/Simple-Binance-Trader/core/botCore.py", line 335, in start
    self.socket_api.start()
  File "/home/Nosynq/Simple-Binance-Trader/core/binance_api/socket_master.py", line 326, in start
    raise websocket.WebSocketTimeoutException('Couldn\'t connect to WS! Exiting.')
websocket._exceptions.WebSocketTimeoutException: Couldn't connect to WS! Exiting.

**Comment by MikeKa** [comment]
I guess I realised that the problem is that I try to use websockets with deployment to pythonanywhere.com. They simply don't support websockets. And recommend to use something like pusher.com for integration. Well, please close if no additions from your side.

**Comment by EasyAI** [comment]
Hello @MikeKa, if the issue is resolved I'm more than happy for this to be closed

**Comment by MikeKa** [comment]
Thanks. Just trying to get it working in the cloud.
