### ISSUE TITLE
Connection failure errors

### ISSUE THREAD

**Issue by fedonkin** [EasyAI/Simple-Binance-Trader#15]
Salut! I started the bot. He worked for two hours. Then the errors started to fly out and he did nothing:
```
.
.
.
2021-09-09 05:01:28,121:root:[BotCore] Connection issue: ('Connection aborted.', TimeoutError(10060, 'Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера', None, 10060, None)).
2021-09-09 05:01:29,275:root:[BotCore] Connection issue: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D553C082B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')).
2021-09-09 05:01:36,249:root:[SOCKET_MASTER] Socket error: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-09-09 05:01:36,297:websocket:error from callback <bound method Binance_SOCK._on_Close of <binance_api.api_master_socket_caller.Binance_SOCK object at 0x000001D553BB9670>>: _on_Close() takes 2 positional arguments but 4 were given
2021-09-09 05:01:36,312:root:[SOCKET_MASTER] Socket error: _on_Close() takes 2 positional arguments but 4 were given
{}
2021-09-09 05:01:40,214:root:[BotCore] Connection issue resolved.
.
.
.
2021-09-09 06:13:37,418:root:[BotCore] Connection issue resolved.
{}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Crea-main\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Crea-main\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
{}
2021-09-09 06:13:52,663:root:[BotCore] Connection issue resolved.
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Crea-main\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Crea-main\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\Crea-main\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Crea-main\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Crea-main\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Crea-main\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Crea-main\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
.
.
.
.
{}
2021-09-09 10:35:37,027:root:[BotCore] Connection issue resolved.
{}
2021-09-09 10:35:51,823:root:[BotCore] Connection issue resolved.
{}
2021-09-09 10:36:07,566:root:[BotCore] Connection issue resolved.
{}
2021-09-09 10:36:22,427:root:[BotCore] Connection issue resolved.

```
The bot writes that the connection problem has been solved, but it does not trade...if only to reboot..

**Comment by fedonkin** [comment]
And it also pops up: 
`
2021-09-09 04:59:37,964:root:[BaseTrader] Completed SELL order. [USDT-SOL]
2021-09-09 04:59:39,514:root:[BINANCE_API_ERROR][CODE: "-2010"][MESSAGE: "Account has insufficient balance for requested action."]

`
But there are enough funds...

**Comment by EasyAI** [comment]
Update for initial connection issue should be fixed under the new api update added.
Can you send me the setup you're using inside settings.conf and remove api details please?
