### ISSUE TITLE
Problem with install on linux

### ISSUE THREAD

**Issue by adiif1** [EasyAI/Simple-Binance-Trader#16]
Hi, i have small problem with this bot
If i itry run bot have error 

```
~/Simple-Binance-Trader-master$ python3 run.py 
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from core import botCore
  File "/home/ubuntu/Simple-Binance-Trader-master/core/botCore.py", line 14, in <module>
    from binance_api import api_master_rest_caller
ImportError: cannot import name 'api_master_rest_caller' from 'binance_api' (unknown location)
```

**Comment by EasyAI** [comment]
Hello, try to re-download the binance api as that has been updated. I will close this off please re-open if the issuer is still there after the update

**Comment by AlvaroG9** [comment]
> Hello, try to re-download the binance api as that has been updated. I will close this off please re-open if the issuer is still there after the update

no work
